# Generated by Django 3.0.6 on 2020-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200517_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='stops',
        ),
        migrations.AddField(
            model_name='flights',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='pitstop', to='flights.Airport'),
        ),
    ]
